version: "3.8"
services: 
    postgresdb: 
        image: "postgres:10.14"
        ports:
            - "5434:5432"
        environment: 
            POSTGRES_DB: takeaway
            POSTGRES_PASSWORD: SX
        networks: 
            - etl-network
    pentahodataintegration:
        build:
            context: ./
            dockerfile: Dockerfile
        networks:
            - etl-network
        depends_on:
            - postgresdb
    metabase:
        container_name: "data-engine_metabase"
        restart: "always"
        image: metabase/metabase
        env_file:
            - ./config/metabase_database.env
        ports:
            - 3000:3000
        networks:
            - etl-network
networks:
    etl-network: